// src/config.js — All game constants and static data catalogs

export const Config = Object.freeze({
    SAVE_KEY: 'mid_designer_save',
    SAVE_VERSION: 1,
    // BUILD_VERSION: bump this string on every deploy that may break existing saves.
    // Format: 'vMAJOR.MINOR' or 'YYYY-MM-DD'
    BUILD_VERSION: 'v0.1',
    BUILD_VERSION_KEY: 'mid_designer_build_version',
    FOREST_SAVE_KEY: 'mid_designer_forest_progress',
    LANGUAGE_SAVE_KEY: 'mid_designer_lang',
    CHAPTERS_SAVE_KEY: 'mid_designer_chapters',

    STATUS: Object.freeze({ REST: 'rest', WORK: 'work', SMOKE: 'smoke' }),
    TASK_CATEGORIES: Object.freeze({
        ORDERS: 'orders',
        STORY: 'story',
        RESEARCH: 'research',
        PROMOTION: 'promotion',
        CONTRACTS: 'contracts',
    }),

    BASE_JOB_CHANCE: 0,
    DEFAULT_UNLOCKED_TASK_TYPES: Object.freeze(['luck']),
    DEFAULT_PRESTIGE_TRANSFER_RATIO: 0.1,

    ORDER_LIFETIME_TICK_MS: 200,
    ZEN_TICK_MS: 1000,
    SMOKE_DURATION_MS: 8000,
    AUTOGEN_TICK_MS: 5000,
    BASE_GENERATION_COOLDOWN_MS: 5000,

    STRESS_MAX: 100,
    STRESS_PER_GENERATION: 8,
    ZEN_DECAY_MIN: 1,
    ZEN_DECAY_MAX: 3,
    CIGARETTE_RELIEF_MIN: 30,
    CIGARETTE_RELIEF_MAX: 50,
    CIGARETTES_PER_PACK: 25,

    EXPONENT_GROWTH: 1.12,
    PAYOUT_SCALE: 26,

    MAX_VISIBLE_ORDERS: 3,

    JOB_SEARCH_MIN_MS: 100,
    JOB_SEARCH_SPAN_MS: 9900,
    JOB_SEARCH_K1_LEVEL: 25,
    JOB_SEARCH_K2_PRESTIGE: 40,

    XP_PER_PAYOUT_RATIO: 0.1,
    XP_BASE_TO_NEXT: 100,
    XP_LEVEL_SCALE_MULT: 1.15,
    XP_LEVEL_LINEAR: 500,

    // ── Day Cycle ──────────────────────────────────────────────────────────
    DAY_PHASE: Object.freeze({ PLANNING: 'planning', WORK: 'work', RESULTS: 'results', REST: 'rest' }),
    WORK_DURATION_MS: 600_000,          // 10 min real = 9 game hours (tunable 3–15 min via testing)
    WORK_HOURS_SPAN: 9,                 // game hours per work session (9:00 → 18:00)
    WEEKEND_CYCLE_DAYS: 5,              // work days per week; accumulated stress resets on day 1
    OFFLINE_AGENT_CAP_BASE_HOURS: 3,    // max offline hours the agent can accumulate (upgradeable)
    COMBO_FAST_REACTION_MS: 500,        // ms threshold to qualify as a "fast" minigen pick
    COMBO_PAYOUT_PER_STEP: 0.05,        // +5% payout multiplier per combo level
    STRESS_ACCUMULATED_RATIO: 0.12,     // fraction of session peak stress added to accumulated stress
    STRESS_HISTORY_INTERVAL_SEC: 5,     // seconds between stress graph data points during WORK
});

export const STORY_ORDERS = [
    {
        id: 'post_portfolio',
        title: 'Опубликовать портфолио',
        taskType: 'story',
        taskCategory: 'story',
        priority: 100,
        generateActionLabel: 'Публиковать',
        durationSec: 65,
        generations: 5,
        requiredGenerations: 5,
        basePayout: 0,
        realPayout: 0,
        xpReward: 10,
        noFailPenalty: true,
        iconUrl: 'images/icons/job/icon-job-story.png',
        chanceBonus: 0.01,
        prestigeTransferRatio: 0.12,
        requiredLevel: 1,
    },
    {
        id: 'green_balls_1',
        title: 'Сгенеровать зеленые шары',
        taskType: 'balls',
        taskCategory: 'story',
        priority: 95,
        ch1Only: true,
        generateActionLabel: 'Работать',
        miniGenTags: ['grnballs1','grnballs2','grnballs3','grnballs4'],
        durationSec: 60,
        generations: 5,
        requiredGenerations: 5,
        basePayout: 800,
        realPayout: 800,
        xpReward: 10,
        noFailPenalty: true,
        iconUrl: 'images/icons/job/icon-job-story.png',
    },
    {
        id: 'green_balls_2',
        title: 'Клиент снова пишет про шарики',
        taskType: 'balls',
        taskCategory: 'story',
        priority: 95,
        ch1Only: true,
        generateActionLabel: 'Работать',
        miniGenTags: ['grnballs1','grnballs2','grnballs3','grnballs4'],
        durationSec: 60,
        generations: 5,
        requiredGenerations: 5,
        basePayout: 800,
        realPayout: 800,
        xpReward: 10,
        noFailPenalty: true,
        iconUrl: 'images/icons/job/icon-job-story.png',
    },
    {
        id: 'call_with_client',
        title: 'Звонок с OutisticDigital',
        taskType: 'call',
        taskCategory: 'story',
        priority: 95,
        ch1Only: true,
        generateActionLabel: 'Говорить',
        durationSec: 300,
        generations: 1,
        requiredGenerations: 1,
        basePayout: 0,
        realPayout: 0,
        xpReward: 0,
        noFailPenalty: true,
        iconUrl: 'images/icons/job/icon-job-story.png',
    },
    {
        id: 'outistic_contract',
        title: 'Подписать контракт с OutisticDigital',
        taskType: 'contract',
        taskCategory: 'story',
        priority: 95,
        ch1Only: true,
        generateActionLabel: 'Подписать',
        durationSec: 120,
        generations: 1,
        requiredGenerations: 1,
        basePayout: 0,
        realPayout: 0,
        xpReward: 0,
        noFailPenalty: true,
        iconUrl: 'images/icons/job/icon-job-story.png',
        unlockSpecialTasks: ['outistic_work'],
    },
    {
        id: 'night_contacts',
        title: 'Предложить ночным клиентам',
        taskType: 'story',
        taskCategory: 'story',
        priority: 90,
        generateActionLabel: 'Предлагать',
        durationSec: 85,
        generations: 6,
        requiredGenerations: 6,
        basePayout: 140,
        realPayout: 220,
        iconUrl: 'images/icons/job/icon-job-story.png',
        unlockTaskTypes: ['casino', 'crypto', 'hh', 'bb'],
        chanceBonus: 0.015,
        prestigeTransferRatio: 0.14,
        requiredLevel: 3,
        requiredKnownness: 1,
        prerequisiteStoryId: 'outistic_contract',
    },
    {
        id: 'big_league_brief',
        title: 'Взять крупный агентский бриф',
        taskType: 'story',
        taskCategory: 'story',
        priority: 80,
        generateActionLabel: 'Создавать',
        durationSec: 105,
        generations: 8,
        requiredGenerations: 8,
        basePayout: 260,
        realPayout: 430,
        iconUrl: 'images/icons/job/icon-job-story.png',
        unlockTaskTypes: ['sb', 'medic', 'alph', 'fsb', 'msc', 'gov', 'gas', 'dark', 'crime', 'vfx', 'luck'],
        chanceBonus: 0.02,
        prestigeTransferRatio: 0.18,
        requiredLevel: 5,
        requiredPrestige: 2,
        requiredKnownness: 2,
        prerequisiteStoryId: 'night_contacts',
    },
];

export const RESEARCH_TASKS = [
    {
        id: 'google_freelance',
        title: 'Загуглить..?',
        taskCategory: 'research',
        taskType: 'research',
        priority: 100,
        generateActionLabel: 'GOOGLE',
        durationSec: 30,
        requiredGenerations: 3,
        realPayout: 0,
        xpReward: 20,
        iconUrl: 'images/icons/job/icon-job-research.png',
        skillPointsReward: 1,
        maxCompletions: 1,
        hidden: true,
    },
    {
        id: 'payment_research',
        title: 'Разобраться с оплатой сервисов',
        taskCategory: 'research',
        taskType: 'research',
        priority: 90,
        generateActionLabel: 'Изучить',
        durationSec: 40,
        requiredGenerations: 3,
        realPayout: 0,
        xpReward: 0,
        iconUrl: 'images/icons/job/icon-job-research.png',
        skillPointsReward: 0,
        maxCompletions: 1,
        hidden: true,
    },
    {
        id: 'find_tshirt',
        title: 'Найти футболку',
        taskCategory: 'research',
        taskType: 'research',
        priority: 85,
        generateActionLabel: 'Искать',
        durationSec: 25,
        requiredGenerations: 1,
        realPayout: 0,
        xpReward: 10,
        iconUrl: 'images/icons/job/icon-job-research.png',
        skillPointsReward: 0,
        maxCompletions: 1,
        hidden: true,
    },
    {
        id: 'market_scan',
        title: 'Сканировать рынок тёплых лидов',
        taskCategory: 'research',
        taskType: 'research',
        priority: 80,
        generateActionLabel: 'Исследовать',
        durationSec: 35,
        requiredGenerations: 3,
        realPayout: -70,
        iconUrl: 'images/icons/job/icon-job-research.png',
        chanceBonus: 0.01,
        skillPointsReward: 2,
        maxCompletions: 4,
        hidden: true,
    },
    {
        id: 'trend_probe',
        title: 'Анализировать тренды по нише',
        taskCategory: 'research',
        taskType: 'research',
        priority: 70,
        generateActionLabel: 'Изучить',
        durationSec: 45,
        requiredGenerations: 4,
        realPayout: -100,
        iconUrl: 'images/icons/job/icon-job-research.png',
        lockedCondition: { type: 'level', value: 2 },
        chanceBonus: 0.012,
        skillPointsReward: 3,
        maxCompletions: 3,
        hidden: true,
    },
    {
        id: 'ai_course',
        title: 'Пройти курс по ИИ',
        taskCategory: 'research',
        taskType: 'research',
        priority: 50,
        generateActionLabel: 'Учиться',
        durationSec: 60,
        requiredGenerations: 10,
        realPayout: -2500,
        iconUrl: 'images/icons/job/icon-job-research.png',
        skillPointsReward: 1,
        repeatable: true,
        hidden: true,
    },
    {
        id: 'ai_agents_1',
        title: 'ИИ Агенты 1',
        taskCategory: 'research',
        taskType: 'research',
        priority: 60,
        generateActionLabel: 'Изучать',
        durationSec: 0,
        requiredGenerations: 25,
        realPayout: -25000,
        iconUrl: 'images/icons/job/icon-job-research.png',
        maxCompletions: 1,
        hidden: true,
    },
    {
        id: 'ai_agents_2',
        title: 'ИИ Агенты 2',
        taskCategory: 'research',
        taskType: 'research',
        priority: 55,
        generateActionLabel: 'Изучать',
        durationSec: 0,
        requiredGenerations: 50,
        realPayout: -35000,
        iconUrl: 'images/icons/job/icon-job-research.png',
        maxCompletions: 1,
        hidden: true,
    },
    {
        id: 'automation',
        title: 'Автоматизация',
        taskCategory: 'research',
        taskType: 'research',
        priority: 58,
        generateActionLabel: 'Изучать',
        durationSec: 0,
        requiredGenerations: 20,
        realPayout: -15000,
        iconUrl: 'images/icons/job/icon-job-research.png',
        maxCompletions: 1,
        hidden: true,
    },
    {
        id: 'ai_exam',
        title: 'Пройти экзамен по ИИ',
        taskCategory: 'research',
        taskType: 'research',
        priority: 45,
        generateActionLabel: 'Сдавать',
        durationSec: 0,
        requiredGenerations: 10,
        realPayout: -10000,
        skillPointsCost: 5,
        expertPointsReward: 1,
        iconUrl: 'images/icons/job/icon-job-research.png',
        repeatable: true,
        hidden: true,
    },
];

export const PROMOTION_TASKS = [
    {
        id: 'spam_cg_chats',
        title: 'Спамить в CG чатах',
        taskCategory: 'promotion',
        taskType: 'spam',
        priority: 100,
        generateActionLabel: 'SPAM',
        durationSec: 50,
        requiredGenerations: 5,
        realPayout: 0,
        xpReward: 15,
        iconUrl: 'images/icons/job/icon-job-promo.png',
        skillPointsReward: 0,
        maxCompletions: 1,
        hidden: true,
    },
    {
        id: 'spam_again',
        title: 'Ещё поспамить',
        taskCategory: 'promotion',
        taskType: 'spam',
        priority: 90,
        generateActionLabel: 'SPAM',
        durationSec: 45,
        requiredGenerations: 5,
        realPayout: 0,
        xpReward: 15,
        iconUrl: 'images/icons/job/icon-job-promo.png',
        chanceBonus: 0.008,
        skillPointsReward: 0,
        maxCompletions: 1,
        hidden: true,
    },
    {
        id: 'showreel_push',
        title: 'Запустить продвижение шоурила',
        taskCategory: 'promotion',
        taskType: 'promotion',
        priority: 80,
        generateActionLabel: 'Продвигать',
        durationSec: 42,
        requiredGenerations: 4,
        realPayout: 95,
        iconUrl: 'images/icons/job/icon-job-promo.png',
        prestigePoolBonus: 10,
        hidden: true,
    },
    {
        id: 'agency_pitch',
        title: 'Предложить агентской сети контакты',
        taskCategory: 'promotion',
        taskType: 'promotion',
        priority: 60,
        generateActionLabel: 'Найти',
        durationSec: 54,
        requiredGenerations: 5,
        realPayout: 140,
        iconUrl: 'images/icons/job/icon-job-promo.png',
        lockedCondition: { type: 'upgrade', value: 'headhunter' },
        prestigePoolBonus: 18,
        hidden: true,
    },
    {
        id: 'post_insta',
        title: 'Постить в инсту',
        taskCategory: 'promotion',
        taskType: 'promotion',
        priority: 75,
        generateActionLabel: 'Постить',
        durationSec: 40,
        requiredGenerations: 5,
        realPayout: 0,
        iconUrl: 'images/icons/job/icon-job-promo.png',
        prestigeReward: 1,   // прямой +1 prestige за выполнение
        repeatable: true,    // бесконечно повторение
        lockedCondition: { type: 'chapter1' },
        hidden: true,
    },
];

// ─────────────────────────────────────────────────────────────
// CONTRACT_TASKS — repeatable studio contracts (OutisticDigital etc.)
// ─────────────────────────────────────────────────────────────
export const CONTRACT_TASKS = Object.freeze([
    {
        id: 'outistic_work',
        title: 'OutisticDigital: Постоянный контент',
        taskCategory: 'contracts',
        generateActionLabel: 'Работать',
        requiredGenerations: 3,   // кликов за один цикл
        realPayout: 1000,         // фиксированная выплата за цикл
        xpReward: 100,
        repeatable: true,
        noFailPenalty: true,
        iconUrl: 'images/icons/job/icon-job-out.png',
    },
]);

/** Access ORDER_TEMPLATES at runtime (populated by orders-data.js script tag) */
export function getOrderTemplates() {
    return window.ORDER_TEMPLATES || [];
}

// ─────────────────────────────────────────────────────────────
// Property locations + items data
// ─────────────────────────────────────────────────────────────

export const PROPERTY_DATA = Object.freeze([
    {
        id: 'abandoned',
        title: 'Заброшка',
        description: 'Место, которое ты называешь домом.',
        baseOwned: true,   // always owned — no purchase needed
        items: Object.freeze([
            { id: 'floor',   title: 'Пол',     price: 30000, src: 'bg/bg-floor-1.png'   },
            { id: 'walls',   title: 'Стены',   price: 25000, src: 'bg/bg-walls-1.png'   },
            { id: 'ceiling', title: 'Потолок', price: 30000, src: 'bg/bg-ceiling-1.png' },
            { id: 'bed',     title: 'Кровать', price:  7000, src: 'bg/bg-bed-1.png'     },
            { id: 'carpet',  title: 'Ковёр',   price:  3000, src: 'bg/bg-carpet-1.png'  },
            { id: 'window',  title: 'Окно',    price: 15000, src: 'bg/bg-window-1.png'  },
        ]),
    },
]);
