// src/upgrades-data.js
// Skill tree node definitions with full 3D world coordinates.
// x, y  — 2D layout (z = 0 for all nodes by default)
// z      — depth in world-space; nodes at 0, decorative layers deeper

window.UPGRADES_DATA = {
    rootNodeId: 'core_designer',
    forestUnlockLevel: 10,

    bgLayers: [
        { src: 'UI/upgrade-menu/space-bg-3.png', worldZ: -2400, blend: 'source-over', alpha: 0.62 },
        { src: 'UI/upgrade-menu/space-bg-2.png', worldZ: -700,  blend: 'screen',       alpha: 0.60 },
        { src: 'UI/upgrade-menu/space-bg-1.png', worldZ: -200,  blend: 'screen',       alpha: 0.94 },
    ],

    branches: {
        core: {
            id: 'core',
            title: 'Core',
        },
        smoking: {
            id: 'smoking',
            title: 'Smoking',
            glowColor: 'rgba(255, 140, 86, 0.33)',
        },
        ai: {
            id: 'ai',
            title: 'AI',
            glowColor: 'rgba(73, 181, 255, 0.34)',
        },
        character: {
            id: 'character',
            title: 'Character',
            glowColor: 'rgba(102, 238, 162, 0.30)',
        },
        forest: {
            id: 'forest',
            title: 'Forest',
            visibleByDefault: false,
            persistentOnWildernessReset: true,
            glowColor: 'rgba(140, 255, 120, 0.28)',
        },
    },

    nodes: [

        // ═══════════════════════════════════════
        //  CORE
        // ═══════════════════════════════════════
        {
            id: 'core_designer',
            branch: 'core',
            x: 0, y: 0, z: 0,
            icon: 'images/cinematic/gg-icon.png',
            title: 'Сердце Дизайна',
            description: 'Отправная точка. Твой рост начинается здесь.',
            costs: {},
            prerequisites: [],
            requirements: {},
            hiddenUntilPurchasedNeighbor: false,
            isRoot: true,
        },

        // ═══════════════════════════════════════
        //  AI BRANCH  — Central (Chat)
        // ═══════════════════════════════════════
        {
            id: 'ai_chatPRO',
            branch: 'ai',
            x: 0, y: -155, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'ChatDJBT PRO',
            description: 'Полная версия. Сокращает кулдаун генерации на 3 секунды.',
            costs: { money: 1000 },
            prerequisites: ['core_designer'],
            requirements: {
                level: 1,
                researchTaskCompleted: 'payment_research',
                researchTaskTitle: 'Разобраться с оплатой сервисов',
            },
            hiddenUntilPurchasedNeighbor: true,
            effects: [
                { type: 'generation_cooldown_reduction_ms', value: 3000 },
            ],
        },
        {
            id: 'ai_chatULTRA',
            branch: 'ai',
            x: 0, y: -295, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'ChatDJBT ULTRA',
            description: '– Скоро –',
            costs: {},
            prerequisites: ['ai_chatPRO'],
            requirements: { level: 5 },
            hiddenUntilPurchasedNeighbor: true,
            effects: [],
            locked: true,
        },

        // ─── AI Left: Auto sub-branch ──────────────────────────
        {
            id: 'ai_vis',
            branch: 'ai',
            x: -165, y: -270, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Компьютерное Зрение',
            prerequisites: ['ai_chatPRO'],
            requirements: { level: 3 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'CV-система подсвечивает правильный вариант в миниген с шансом 50%.',
                    costs: { money: 10000 },
                    effects: [{ type: 'ai_vis_accuracy_set', value: 0.50 }],
                },
                {
                    description: 'Шанс подсветки правильного варианта: 60%.',
                    costs: { money: 15000, skillPoints: 1 },
                    effects: [{ type: 'ai_vis_accuracy_set', value: 0.60 }],
                },
                {
                    description: 'Шанс подсветки: 70%.',
                    costs: { money: 20000, skillPoints: 2 },
                    effects: [{ type: 'ai_vis_accuracy_set', value: 0.70 }],
                },
                {
                    description: 'Шанс подсветки: 90%.',
                    costs: { money: 50000, skillPoints: 5 },
                    effects: [{ type: 'ai_vis_accuracy_set', value: 0.90 }],
                },
                {
                    description: 'Шанс подсветки: 95%.',
                    costs: { money: 100000, skillPoints: 10 },
                    effects: [{ type: 'ai_vis_accuracy_set', value: 0.95 }],
                },
            ],
        },
        {
            id: 'ai_autogen',
            branch: 'ai',
            x: -165, y: -405, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Автогенератор',
            prerequisites: ['ai_vis'],
            requirements: { level: 3 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Разблокирует автогенератор. Нажимает кнопку каждые 5 сек. Таймер выбора в миниген: 3 сек.',
                    costs: { money: 10000, skillPoints: 1 },
                    effects: [
                        { type: 'unlock_feature', feature: 'autogen' },
                        { type: 'autogen_interval_ms_set', value: 5000 },
                        { type: 'minigen_choice_timer_ms_set', value: 3000 },
                    ],
                },
                {
                    description: 'Интервал автогена: 2 сек.',
                    costs: { money: 50000, skillPoints: 5 },
                    effects: [{ type: 'autogen_interval_ms_set', value: 2000 }],
                },
                {
                    description: 'Интервал автогена: 1 сек.',
                    costs: { money: 100000, expertPoints: 1 },
                    effects: [{ type: 'autogen_interval_ms_set', value: 1000 }],
                },
                {
                    description: 'Интервал автогена: 0.5 сек.',
                    costs: { money: 500000, expertPoints: 5 },
                    effects: [{ type: 'autogen_interval_ms_set', value: 500 }],
                },
                {
                    description: 'Интервал автогена: 0 — непрерывно.',
                    costs: { money: 2500000, expertPoints: 10 },
                    effects: [{ type: 'autogen_interval_ms_set', value: 0 }],
                },
            ],
        },
        {
            id: 'ai_autoboost',
            branch: 'ai',
            x: -295, y: -510, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Авто-ускоритель',
            prerequisites: ['ai_autogen'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Таймер выбора в миниген (авто): 2.5 сек.',
                    costs: { money: 10000, skillPoints: 1 },
                    effects: [{ type: 'minigen_choice_timer_ms_set', value: 2500 }],
                },
                {
                    description: 'Таймер выбора: 2 сек.',
                    costs: { money: 50000, skillPoints: 5 },
                    effects: [{ type: 'minigen_choice_timer_ms_set', value: 2000 }],
                },
                {
                    description: 'Таймер выбора: 1 сек.',
                    costs: { money: 100000, expertPoints: 1 },
                    effects: [{ type: 'minigen_choice_timer_ms_set', value: 1000 }],
                },
                {
                    description: 'Таймер выбора: 0.5 сек.',
                    costs: { money: 500000, expertPoints: 5 },
                    effects: [{ type: 'minigen_choice_timer_ms_set', value: 500 }],
                },
                {
                    description: 'Таймер выбора: 0.25 сек.',
                    costs: { money: 5000000, expertPoints: 10 },
                    effects: [{ type: 'minigen_choice_timer_ms_set', value: 250 }],
                },
            ],
        },
        {
            id: 'ai_autobatch',
            branch: 'ai',
            x: -165, y: -540, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Авто-серия',
            prerequisites: ['ai_autogen'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: '+1 генерация за каждое авто-нажатие (итого +1).',
                    costs: { money: 50000, skillPoints: 1 },
                    effects: [{ type: 'autogen_batch_bonus', value: 1 }],
                },
                {
                    description: '+1 генерация (итого +2).',
                    costs: { money: 150000, skillPoints: 5 },
                    effects: [{ type: 'autogen_batch_bonus', value: 1 }],
                },
                {
                    description: '+2 генерации (итого +4).',
                    costs: { money: 500000, expertPoints: 1 },
                    effects: [{ type: 'autogen_batch_bonus', value: 2 }],
                },
                {
                    description: '+4 генерации (итого +8).',
                    costs: { money: 10000000, expertPoints: 5 },
                    effects: [{ type: 'autogen_batch_bonus', value: 4 }],
                },
            ],
        },
        {
            id: 'ai_autoresearch',
            branch: 'ai',
            x: -60, y: -510, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Авто-исследование',
            prerequisites: ['ai_autogen'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: '+10 XP в пул исследования за каждый правильный выбор в миниген.',
                    costs: { money: 5000, skillPoints: 1 },
                    effects: [{ type: 'autoresearch_xp_per_choice', value: 10 }],
                },
                {
                    description: '+50 XP за правильный выбор.',
                    costs: { money: 25000, skillPoints: 5 },
                    effects: [{ type: 'autoresearch_xp_per_choice', value: 50 }],
                },
                {
                    description: '+100 XP за правильный выбор.',
                    costs: { money: 100000, skillPoints: 15, expertPoints: 5 },
                    effects: [{ type: 'autoresearch_xp_per_choice', value: 100 }],
                },
                {
                    description: '+500 XP за правильный выбор.',
                    costs: { money: 1000000, expertPoints: 15 },
                    effects: [{ type: 'autoresearch_xp_per_choice', value: 500 }],
                },
                {
                    description: '+1000 XP за правильный выбор.',
                    costs: { money: 15000000, expertPoints: 30 },
                    effects: [{ type: 'autoresearch_xp_per_choice', value: 1000 }],
                },
            ],
        },
        {
            id: 'ai_agent',
            branch: 'ai',
            x: -345, y: -360, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'ИИ-Агент',
            description: 'Каждые 30 секунд начисляет 25% от суммарного заработка за этот период.',
            costs: { money: 15000, skillPoints: 1 },
            prerequisites: ['ai_vis'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            effects: [
                { type: 'unlock_feature', feature: 'agent_income' },
                { type: 'agent_income_percent_set', value: 25 },
                { type: 'agent_income_interval_sec_set', value: 30 },
            ],
        },
        {
            id: 'ai_agentboost',
            branch: 'ai',
            x: -290, y: -480, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Агент+',
            prerequisites: ['ai_autogen', 'ai_agent'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Интервал агента: 25 сек.',
                    costs: { money: 50000, skillPoints: 2 },
                    effects: [{ type: 'agent_income_interval_sec_set', value: 25 }],
                },
                {
                    description: 'Интервал агента: 20 сек.',
                    costs: { money: 250000, skillPoints: 5 },
                    effects: [{ type: 'agent_income_interval_sec_set', value: 20 }],
                },
                {
                    description: 'Интервал агента: 15 сек.',
                    costs: { money: 1000000, skillPoints: 5, expertPoints: 1 },
                    effects: [{ type: 'agent_income_interval_sec_set', value: 15 }],
                },
                {
                    description: 'Интервал агента: 10 сек.',
                    costs: { money: 5000000, expertPoints: 2 },
                    effects: [{ type: 'agent_income_interval_sec_set', value: 10 }],
                },
                {
                    description: 'Интервал агента: 5 сек.',
                    costs: { money: 25000000, expertPoints: 5 },
                    effects: [{ type: 'agent_income_interval_sec_set', value: 5 }],
                },
            ],
        },
        {
            id: 'ai_agentbuff',
            branch: 'ai',
            x: -395, y: -570, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Агент++',
            prerequisites: ['ai_agentboost'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Доля агента: 50%.',
                    costs: { money: 100000 },
                    requiredLevel: 4,
                    effects: [{ type: 'agent_income_percent_set', value: 50 }],
                },
                {
                    description: 'Доля агента: 100%.',
                    costs: { money: 5000000 },
                    requiredLevel: 4,
                    effects: [{ type: 'agent_income_percent_set', value: 100 }],
                },
                {
                    description: 'Доля агента: 200%.',
                    costs: { money: 50000000 },
                    requiredLevel: 6,
                    effects: [{ type: 'agent_income_percent_set', value: 200 }],
                },
                {
                    description: 'Доля агента: 350%.',
                    costs: { money: 250000000 },
                    requiredLevel: 10,
                    effects: [{ type: 'agent_income_percent_set', value: 350 }],
                },
                {
                    description: 'Доля агента: 500%.',
                    costs: { money: 1000000000 },
                    requiredLevel: 15,
                    effects: [{ type: 'agent_income_percent_set', value: 500 }],
                },
            ],
        },
        {
            id: 'ai_headhunter',
            branch: 'ai',
            x: -450, y: -440, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Хедхантер',
            prerequisites: ['ai_agent'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Хедхантер присылает заказы каждые 25 сек.',
                    costs: { money: 50000 },
                    requiredLevel: 4,
                    effects: [{ type: 'headhunter_interval_sec_set', value: 25 }],
                },
                {
                    description: 'Интервал хедхантера: 15 сек.',
                    costs: { money: 500000 },
                    requiredLevel: 5,
                    effects: [{ type: 'headhunter_interval_sec_set', value: 15 }],
                },
                {
                    description: 'Интервал хедхантера: 5 сек.',
                    costs: { money: 25000000 },
                    requiredLevel: 6,
                    effects: [{ type: 'headhunter_interval_sec_set', value: 5 }],
                },
                {
                    description: 'Интервал хедхантера: 2 сек.',
                    costs: { money: 500000000 },
                    requiredLevel: 15,
                    effects: [{ type: 'headhunter_interval_sec_set', value: 2 }],
                },
                {
                    description: 'Интервал хедхантера: 1 сек.',
                    costs: { money: 10000000000 },
                    requiredLevel: 20,
                    effects: [{ type: 'headhunter_interval_sec_set', value: 1 }],
                },
            ],
        },
        {
            id: 'ai_network',
            branch: 'ai',
            x: -420, y: -255, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Сеть',
            description: 'Разблокирует меню и механику Сети. — Глава 3 —',
            costs: { money: 250000 },
            prerequisites: ['ai_agent'],
            requirements: { level: 5, chapter3Unlocked: true },
            hiddenUntilPurchasedNeighbor: true,
            effects: [{ type: 'unlock_feature', feature: 'network' }],
            locked: true,
        },

        // ─── AI Right: Manual sub-branch ──────────────────────
        {
            id: 'ai_tokens',
            branch: 'ai',
            x: 165, y: -270, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Доп Токены',
            prerequisites: ['ai_chatPRO'],
            requirements: { level: 3 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Кулдаун кнопки −100 мс.',
                    costs: { money: 1500 },
                    effects: [{ type: 'generation_cooldown_reduction_ms', value: 100 }],
                },
                {
                    description: 'Кулдаун −100 мс (итого −200 мс).',
                    costs: { money: 2500 },
                    effects: [{ type: 'generation_cooldown_reduction_ms', value: 100 }],
                },
                {
                    description: 'Кулдаун −300 мс (итого −500 мс).',
                    costs: { money: 5000, skillPoints: 1 },
                    effects: [{ type: 'generation_cooldown_reduction_ms', value: 300 }],
                },
                {
                    description: 'Кулдаун −500 мс (итого −1000 мс).',
                    costs: { money: 25000, skillPoints: 3 },
                    effects: [{ type: 'generation_cooldown_reduction_ms', value: 500 }],
                },
                {
                    description: 'Кулдаун −500 мс (итого −1500 мс).',
                    costs: { money: 100000, expertPoints: 1 },
                    effects: [{ type: 'generation_cooldown_reduction_ms', value: 500 }],
                },
            ],
        },
        {
            id: 'ai_batch',
            branch: 'ai',
            x: 165, y: -405, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Серия',
            prerequisites: ['ai_tokens'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: '+1 генерация за нажатие (итого +1).',
                    costs: { money: 10000, skillPoints: 1 },
                    effects: [{ type: 'generations_per_press_bonus', value: 1 }],
                },
                {
                    description: '+1 генерация (итого +2).',
                    costs: { money: 50000, skillPoints: 3 },
                    effects: [{ type: 'generations_per_press_bonus', value: 1 }],
                },
                {
                    description: '+2 генерации (итого +4).',
                    costs: { money: 300000, expertPoints: 1 },
                    effects: [{ type: 'generations_per_press_bonus', value: 2 }],
                },
                {
                    description: '+5 генераций (итого +9).',
                    costs: { money: 1000000, expertPoints: 5 },
                    effects: [{ type: 'generations_per_press_bonus', value: 5 }],
                },
                {
                    description: '+10 генераций (итого +19).',
                    costs: { money: 5000000, expertPoints: 10 },
                    effects: [{ type: 'generations_per_press_bonus', value: 10 }],
                },
            ],
        },
        {
            id: 'ai_heat',
            branch: 'ai',
            x: 290, y: -510, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Жар',
            description: 'При нагреве кнопки повышается шанс на 1 доп генерацию — от 0.1 до 1 в зависимости от уровня жара.',
            costs: { money: 15000, skillPoints: 1 },
            prerequisites: ['ai_batch'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            effects: [{ type: 'unlock_feature', feature: 'heat_bonus_gen' }],
        },
        {
            id: 'ai_neural',
            branch: 'ai',
            x: 60, y: -405, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Нейронная Память',
            description: 'Ручной выбор лучших вариантов в миниген накапливает бонус к выплате +0.5% за выбор (макс. 100%). Стак сбрасывается при ошибке.',
            costs: { money: 15000, skillPoints: 2 },
            prerequisites: ['ai_tokens'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            effects: [
                { type: 'unlock_feature', feature: 'neural_payout_stack' },
                { type: 'neural_payout_per_choice', value: 0.005 },
                { type: 'neural_payout_max_stack', value: 1.00 },
            ],
        },
        {
            id: 'ai_connect',
            branch: 'ai',
            x: 195, y: -635, z: 0,
            icon: 'images/cinematic/chatdjbt-icon.png',
            title: 'Интерлинкд',
            description: 'Применяет все бонусы "мануальной" генерации к "автоматической". — Глава 3 —',
            costs: {},
            prerequisites: ['ai_heat', 'ai_neural', 'gg_willpower'],
            requirements: { chapter3Unlocked: true },
            hiddenUntilPurchasedNeighbor: true,
            effects: [],
            locked: true,
        },

        // ═══════════════════════════════════════
        //  SMOKING BRANCH
        // ═══════════════════════════════════════
        {
            id: 'cig_lungs',
            branch: 'smoking',
            x: -215, y: 0, z: 0,
            icon: 'images/icons/icon-good-cigs.png',
            title: 'Лёгкие',
            description: 'Во время перекура можно нажимать основную кнопку, чтобы ускорить курение (механика жара кнопки).',
            costs: { butts: 10 },
            prerequisites: ['core_designer'],
            requirements: { level: 2 },
            hiddenUntilPurchasedNeighbor: true,
            effects: [{ type: 'unlock_feature', feature: 'smoke_speed_click' }],
        },

        // — Top sub-branch —
        {
            id: 'cig_kaif',
            branch: 'smoking',
            x: -330, y: -115, z: 0,
            icon: 'images/icons/icon-good-cigs.png',
            title: 'Кайф',
            prerequisites: ['cig_lungs'],
            requirements: { level: 3 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Перекур снимает +5 стресса.',
                    costs: { butts: 5 },
                    effects: [{ type: 'smoke_relief_bonus', value: 5 }],
                },
                {
                    description: '+10 стресса (итого +15).',
                    costs: { butts: 15 },
                    effects: [{ type: 'smoke_relief_bonus', value: 10 }],
                },
                {
                    description: '+15 стресса (итого +30).',
                    costs: { butts: 20 },
                    effects: [{ type: 'smoke_relief_bonus', value: 15 }],
                },
                {
                    description: '+25 стресса (итого +55).',
                    costs: { butts: 50 },
                    effects: [{ type: 'smoke_relief_bonus', value: 25 }],
                },
                {
                    description: '+50 стресса (итого +105).',
                    costs: { butts: 100 },
                    effects: [{ type: 'smoke_relief_bonus', value: 50 }],
                },
            ],
        },
        {
            id: 'cig_memory',
            branch: 'smoking',
            x: -330, y: -240, z: 0,
            icon: 'images/icons/icon-good-cigs.png',
            title: 'Мышечная Память',
            prerequisites: ['cig_kaif'],
            requirements: { level: 3 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'После перекура 3 сек стресс рассеивается на +10% быстрее.',
                    costs: { butts: 5 },
                    requiredLevel: 3,
                    effects: [{ type: 'post_smoke_decay_boost_pct', value: 0.10 }],
                },
                {
                    description: 'Буст рассеивания: +25%.',
                    costs: { butts: 10 },
                    requiredLevel: 3,
                    effects: [{ type: 'post_smoke_decay_boost_pct', value: 0.25 }],
                },
                {
                    description: 'Буст рассеивания: +50%.',
                    costs: { butts: 15 },
                    requiredLevel: 4,
                    effects: [{ type: 'post_smoke_decay_boost_pct', value: 0.50 }],
                },
                {
                    description: 'Буст рассеивания: +100%.',
                    costs: { butts: 50 },
                    requiredLevel: 4,
                    effects: [{ type: 'post_smoke_decay_boost_pct', value: 1.00 }],
                },
            ],
        },

        // — Bottom sub-branch —
        {
            id: 'cig_speed',
            branch: 'smoking',
            x: -330, y: 115, z: 0,
            icon: 'images/icons/icon-good-cigs.png',
            title: 'Скоростной Перекур',
            prerequisites: ['cig_lungs'],
            requirements: { level: 3 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Скорость перекура ×1.25 (итого ×1.25).',
                    costs: { butts: 15 },
                    requiredLevel: 3,
                    effects: [{ type: 'smoke_speed_set', value: 1.25 }],
                },
                {
                    description: 'Скорость перекура ×1.5 от базовой.',
                    costs: { butts: 20 },
                    requiredLevel: 3,
                    effects: [{ type: 'smoke_speed_set', value: 1.50 }],
                },
                {
                    description: 'Скорость перекура ×2 от базовой.',
                    costs: { butts: 50 },
                    requiredLevel: 4,
                    effects: [{ type: 'smoke_speed_set', value: 2.00 }],
                },
            ],
        },
        {
            id: 'cig_abst',
            branch: 'smoking',
            x: -450, y: 235, z: 0,
            icon: 'images/icons/icon-good-cigs.png',
            title: 'Абстиненция',
            prerequisites: ['cig_speed'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Можно пропустить фазу курения 1 раз (стресс не снимается).',
                    costs: { butts: 10, skillPoints: 1 },
                    effects: [{ type: 'smoke_skip_charges_max', value: 1 }],
                },
                {
                    description: 'До 2 пропусков.',
                    costs: { butts: 25, skillPoints: 1 },
                    effects: [{ type: 'smoke_skip_charges_max', value: 2 }],
                },
                {
                    description: 'До 3 пропусков.',
                    costs: { butts: 50, skillPoints: 2 },
                    effects: [{ type: 'smoke_skip_charges_max', value: 3 }],
                },
                {
                    description: 'До 5 пропусков.',
                    costs: { butts: 100, expertPoints: 1 },
                    effects: [{ type: 'smoke_skip_charges_max', value: 5 }],
                },
            ],
        },
        {
            id: 'cig_slowmo',
            branch: 'smoking',
            x: -215, y: 235, z: 0,
            icon: 'images/icons/icon-good-cigs.png',
            title: 'Слоу-Мо',
            prerequisites: ['cig_speed'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'При начале перекура во время дедлайна — таймер замораживается на 1 сек.',
                    costs: { butts: 15 },
                    effects: [{ type: 'deadline_pause_on_smoke_sec', value: 1 }],
                },
                {
                    description: 'Пауза таймера: 2 сек.',
                    costs: { butts: 25 },
                    effects: [{ type: 'deadline_pause_on_smoke_sec', value: 2 }],
                },
                {
                    description: 'Пауза таймера: 3 сек.',
                    costs: { butts: 100, expertPoints: 1 },
                    effects: [{ type: 'deadline_pause_on_smoke_sec', value: 3 }],
                },
            ],
        },

        // ═══════════════════════════════════════
        //  CHARACTER BRANCH
        // ═══════════════════════════════════════
        {
            id: 'gg_self_aware',
            branch: 'character',
            x: 220, y: 0, z: 0,
            icon: 'images/cinematic/gg-icon.png',
            title: 'Осознанность',
            prerequisites: ['core_designer'],
            requirements: { level: 2 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Максимальный стресс +10.',
                    costs: { money: 1500, skillPoints: 1 },
                    requiredLevel: 2,
                    effects: [{ type: 'stress_pool_bonus', value: 10 }],
                },
                {
                    description: 'Максимальный стресс ещё +15.',
                    costs: { money: 5000, skillPoints: 1 },
                    requiredLevel: 3,
                    effects: [{ type: 'stress_pool_bonus', value: 15 }],
                },
                {
                    description: 'Максимальный стресс ещё +25.',
                    costs: { money: 50000, skillPoints: 2 },
                    requiredLevel: 4,
                    effects: [{ type: 'stress_pool_bonus', value: 25 }],
                },
                {
                    description: 'Максимальный стресс ещё +25.',
                    costs: { money: 250000, skillPoints: 3 },
                    requiredLevel: 5,
                    effects: [{ type: 'stress_pool_bonus', value: 25 }],
                },
                {
                    description: 'Максимальный стресс ещё +25.',
                    costs: { money: 1000000, skillPoints: 5 },
                    requiredLevel: 7,
                    effects: [{ type: 'stress_pool_bonus', value: 25 }],
                },
            ],
        },
        {
            id: 'gg_stoic',
            branch: 'character',
            x: 220, y: -165, z: 0,
            icon: 'images/cinematic/gg-icon.png',
            title: 'Стоик',
            prerequisites: ['gg_self_aware'],
            requirements: { level: 2 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Скорость рассеивания стресса: +15%.',
                    costs: { skillPoints: 1 },
                    requiredLevel: 2,
                    effects: [{ type: 'stress_decay_bonus_set', value: 0.15 }],
                },
                {
                    description: 'Скорость рассеивания: +50%.',
                    costs: { money: 10000, skillPoints: 1 },
                    requiredLevel: 3,
                    effects: [{ type: 'stress_decay_bonus_set', value: 0.50 }],
                },
                {
                    description: 'Скорость рассеивания: +100%.',
                    costs: { money: 25000, skillPoints: 1 },
                    requiredLevel: 4,
                    effects: [{ type: 'stress_decay_bonus_set', value: 1.00 }],
                },
                {
                    description: 'Скорость рассеивания: +150%.',
                    costs: { money: 100000, skillPoints: 3 },
                    requiredLevel: 4,
                    effects: [{ type: 'stress_decay_bonus_set', value: 1.50 }],
                },
                {
                    description: 'Скорость рассеивания: +250%.',
                    costs: { money: 500000, skillPoints: 5 },
                    requiredLevel: 5,
                    effects: [{ type: 'stress_decay_bonus_set', value: 2.50 }],
                },
            ],
        },
        {
            id: 'gg_contractor',
            branch: 'character',
            x: 375, y: -165, z: 0,
            icon: 'images/cinematic/gg-icon.png',
            title: 'Контрактор',
            prerequisites: ['gg_stoic'],
            requirements: { level: 2 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Увеличивает доход от контрактов на 50%.',
                    costs: { skillPoints: 1 },
                    requiredLevel: 2,
                    effects: [{ type: 'contract_payout_bonus_pct', value: 0.50 }],
                },
                {
                    description: 'Доход от контрактов: +100%.',
                    costs: { skillPoints: 3 },
                    requiredLevel: 3,
                    effects: [{ type: 'contract_payout_bonus_pct', value: 1.00 }],
                },
                {
                    description: 'Доход от контрактов: +250%.',
                    costs: { skillPoints: 5 },
                    requiredLevel: 4,
                    effects: [{ type: 'contract_payout_bonus_pct', value: 2.50 }],
                },
                {
                    description: 'Доход от контрактов: +500%.',
                    costs: { expertPoints: 1 },
                    requiredLevel: 5,
                    effects: [{ type: 'contract_payout_bonus_pct', value: 5.00 }],
                },
                {
                    description: 'Доход от контрактов: +1500%.',
                    costs: { expertPoints: 3 },
                    requiredLevel: 7,
                    effects: [{ type: 'contract_payout_bonus_pct', value: 15.00 }],
                },
            ],
        },
        {
            id: 'gg_reflexia',
            branch: 'character',
            x: 220, y: -310, z: 0,
            icon: 'images/cinematic/gg-icon.png',
            title: 'Рефлексия',
            description: 'Разблокирует задачу исследования на EP: "Пройти экзамен по ИИ".',
            costs: { money: 15000, skillPoints: 1 },
            prerequisites: ['gg_stoic'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            effects: [{ type: 'unlock_research_task', taskId: 'ai_exam' }],
        },
        {
            id: 'gg_focus',
            branch: 'character',
            x: 60, y: -440, z: 0,
            icon: 'images/cinematic/gg-icon.png',
            title: 'Фокус',
            description: 'Правильные угадывания в миниген накапливают шанс пропустить перекур (0→1, распад 0.1/сек).',
            costs: { skillPoints: 3 },
            prerequisites: ['gg_reflexia'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            effects: [{ type: 'unlock_feature', feature: 'focus_smoke_skip' }],
        },
        {
            id: 'gg_willpower',
            branch: 'character',
            x: 180, y: -440, z: 0,
            icon: 'images/cinematic/gg-icon.png',
            title: 'Сила Воли',
            prerequisites: ['gg_reflexia'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: '5% шанс не получить стресс за генерацию.',
                    costs: { skillPoints: 1 },
                    requiredLevel: 4,
                    effects: [{ type: 'generation_nostress_chance_set', value: 0.05 }],
                },
                {
                    description: 'Шанс: 10%.',
                    costs: { skillPoints: 2 },
                    requiredLevel: 4,
                    effects: [{ type: 'generation_nostress_chance_set', value: 0.10 }],
                },
                {
                    description: 'Шанс: 15%.',
                    costs: { skillPoints: 3 },
                    requiredLevel: 4,
                    effects: [{ type: 'generation_nostress_chance_set', value: 0.15 }],
                },
                {
                    description: 'Шанс: 25%.',
                    costs: { skillPoints: 5 },
                    requiredLevel: 5,
                    effects: [{ type: 'generation_nostress_chance_set', value: 0.25 }],
                },
                {
                    description: 'Шанс: 50%.',
                    costs: { expertPoints: 1 },
                    requiredLevel: 7,
                    effects: [{ type: 'generation_nostress_chance_set', value: 0.50 }],
                },
            ],
        },
        {
            id: 'gg_speed',
            branch: 'character',
            x: 305, y: -440, z: 0,
            icon: 'images/cinematic/gg-icon.png',
            title: 'Замедление',
            description: 'При высоком стрессе таймер дедлайна тикает медленнее.',
            costs: { expertPoints: 1 },
            prerequisites: ['gg_reflexia'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            effects: [{ type: 'unlock_feature', feature: 'stress_deadline_slowdown' }],
        },
        {
            id: 'gg_int',
            branch: 'character',
            x: 415, y: -440, z: 0,
            icon: 'images/cinematic/gg-icon.png',
            title: 'Интеллект',
            prerequisites: ['gg_reflexia'],
            requirements: { level: 4 },
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: '+25% XP, поступающего в пул исследования.',
                    costs: { skillPoints: 1 },
                    effects: [{ type: 'research_pool_xp_bonus_pct', value: 0.25 }],
                },
                {
                    description: '+50% XP в пул.',
                    costs: { skillPoints: 2 },
                    effects: [{ type: 'research_pool_xp_bonus_pct', value: 0.50 }],
                },
                {
                    description: '+100% XP в пул.',
                    costs: { skillPoints: 3 },
                    effects: [{ type: 'research_pool_xp_bonus_pct', value: 1.00 }],
                },
            ],
        },
        {
            id: 'gg_conf',
            branch: 'character',
            x: 510, y: -440, z: 0,
            icon: 'images/cinematic/gg-icon.png',
            title: 'Уверенность',
            prerequisites: ['gg_reflexia'],
            requirements: {},
            hiddenUntilPurchasedNeighbor: true,
            tiers: [
                {
                    description: 'Снижает прирост стресса от кликов на 2 (минимум 1 за клик).',
                    costs: { skillPoints: 1 },
                    effects: [{ type: 'stress_per_gen_reduction', value: 2 }],
                },
                {
                    description: 'Снижение стресса от кликов: −3 (минимум 1).',
                    costs: { skillPoints: 3 },
                    effects: [{ type: 'stress_per_gen_reduction', value: 3 }],
                },
                {
                    description: 'Снижение стресса от кликов: −5 (минимум 1).',
                    costs: { expertPoints: 1 },
                    effects: [{ type: 'stress_per_gen_reduction', value: 5 }],
                },
            ],
        },

        // ═══════════════════════════════════════
        //  FOREST BRANCH (скрытая)
        // ═══════════════════════════════════════
        {
            id: 'forest_root',
            branch: 'forest',
            x: 0, y: 185, z: 0,
            icon: 'images/cinematic/gg-icon.png',
            title: 'В Лес',
            description: 'Уйти в глушь. Сбросить всё ради нового старта.',
            costs: { money: 100 },
            prerequisites: ['core_designer'],
            requirements: { level: 10 },
            hiddenUntilPurchasedNeighbor: false,
            effects: [{ type: 'forest_unlock', value: true }],
        },

    ],
};
